name: CI

on:
  push:
    branches:
      - main
      - experimental
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test build and types
        run: npm test

      - name: Integration test
        run: xvfb-run -a npm run test:integration

      - name: E2E test
        run: xvfb-run -a npm run test:e2e
